### ISSUE TITLE
compilation error on minnow-velocity branch

### ISSUE THREAD

**Issue by daskelly** [COMBINE-lab/minnow#12]
I am working on MacOS 10.15. My `cmake` version is 3.17.3 and `gcc --version` returns `Apple clang version 11.0.3`.

I **am** able to successfully compile the `refactor` branch of minnow using instructions provided for Manual Installation in the README. However, I am running into an error specifically when trying to compile the `minnow-velocity` branch. `cmake` works for a while and then outputs the following:
```
[  5%] No patch step for 'libtbb'
[  7%] No update step for 'libtbb'
[  8%] No configure step for 'libtbb'
[ 10%] Performing build step for 'libtbb'
Created the ./build/LIBS_release directory
../../build/Makefile.tbb:28: CONFIG: cfg=release arch=intel64 compiler=gcc target=macos runtime=cc11.0.3_os10.15.4
clang: error: unknown argument: '-flifetime-dse=1'
make[4]: *** [concurrent_hash_map.o] Error 1
make[3]: *** [tbb] Error 2
make[2]: *** [libtbb-prefix/src/libtbb-stamp/libtbb-build] Error 2
make[1]: *** [CMakeFiles/libtbb.dir/all] Error 2
make: *** [all] Error 2
```
Any suggestions for how I might proceed?

**Comment by daskelly** [comment]
FWIW, when compiling the `minnow-velocity` branch, I followed the same instructions in the README except after cloning the repo I executed `git checkout minnow-velocity`.

**Comment by hiraksarkar** [comment]
Hi @daskelly , 

It should be fine, but I am checking if there is anything changed in the tbb front. I generally check in on Linux.

**Comment by hiraksarkar** [comment]
Hi @daskelly Can you please pull and try now, it's compiling correctly on my mac.

**Comment by daskelly** [comment]
Hi @hiraksarkar it is working now, thank you for your efforts!
